# Class: vsftpd
#
# Install, enable and configure a vsftpd FTP server instance.
#
# Parameters:
#  see vsftpd.conf(5) for details about what the available parameters do.
# Sample Usage :
#  include vsftpd
#  class { 'vsftpd':
#    anonymous_enable  => 'NO',
#    write_enable      => 'YES',
#    ftpd_banner       => 'Marmotte FTP Server',
#    chroot_local_user => 'YES',
#  }
#
class vsftpd (
  $confdir                   = $::vsftpd::params::confdir,
  $package_name              = $::vsftpd::params::package_name,
  $service_name              = $::vsftpd::params::service_name,
  $template                  = 'vsftpd/vsftpd.conf.erb',

  # vsftpd.conf options
  $anonymous_enable          = $::vsftpd::params::anonymous_enable,
  $local_enable              = $::vsftpd::params::local_enable,
  $write_enable              = $::vsftpd::params::write_enable,
  $local_umask               = $::vsftpd::params::local_umask,
  $anon_upload_enable        = $::vsftpd::params::anon_upload_enable,
  $anon_mkdir_write_enable   = $::vsftpd::params::anon_mkdir_write_enable,
  $dirmessage_enable         = $::vsftpd::params::dirmessage_enable,
  $xferlog_enable            = $::vsftpd::params::xferlog_enable,
  $connect_from_port_20      = $::vsftpd::params::connect_from_port_20,
  $chown_uploads             = $::vsftpd::params::chown_uploads,
  $chown_username            = $::vsftpd::params::chown_username,
  $xferlog_file              = $::vsftpd::params::xferlog_file,
  $xferlog_std_format        = $::vsftpd::params::xferlog_std_format,
  $idle_session_timeout      = $::vsftpd::params::idle_session_timeout,
  $data_connection_timeout   = $::vsftpd::params::data_connection_timeout,
  $nopriv_user               = $::vsftpd::params::nopriv_user,
  $async_abor_enable         = $::vsftpd::params::async_abor_enable,
  $ascii_upload_enable       = $::vsftpd::params::ascii_upload_enable,
  $ascii_download_enable     = $::vsftpd::params::ascii_download_enable,
  $ftpd_banner               = $::vsftpd::params::ftpd_banner,
  $chroot_local_user         = $::vsftpd::params::chroot_local_user,
  $chroot_list_enable        = $::vsftpd::params::chroot_list_enable,
  $chroot_list_file          = $::vsftpd::params::chroot_list_file,
  $ls_recurse_enable         = $::vsftpd::params::ls_recurse_enable,
  $listen_address            = $::vsftpd::params::listen_address,
  $listen                    = $::vsftpd::params::listen,
  $listen_port               = $::vsftpd::params::listen_port,
  $pam_service_name          = $::vsftpd::params::pam_service_name,
  $userlist_enable           = $::vsftpd::params::userlist_enable,
  $userlist_deny             = $::vsftpd::params::userlist_deny,
  $tcp_wrappers              = $::vsftpd::params::tcp_wrappers,
  $hide_file                 = $::vsftpd::params::hide_file,
  $hide_ids                  = $::vsftpd::params::hide_ids,
  $setproctitle_enable       = $::vsftpd::params::setproctitle_enable,
  $text_userdb_names         = $::vsftpd::params::text_userdb_names,
  $max_clients               = $::vsftpd::params::max_clients,
  $max_per_ip                = $::vsftpd::params::max_per_ip,
  $pasv_min_port             = $::vsftpd::params::pasv_min_port,
  $pasv_max_port             = $::vsftpd::params::pasv_max_port,
  $ftp_username              = $::vsftpd::params::ftp_username,
  $banner_file               = $::vsftpd::params::banner_file,
  $allow_writeable_chroot    = $::vsftpd::params::allow_writeable_chroot,
  $ssl_request_cert          = $::vsftpd::params::ssl_request_cert,
  $anon_world_readable_only  = $::vsftpd::params::anon_world_readable_only,
  $background                = $::vsftpd::params::background,
  $check_shell               = $::vsftpd::params::check_shell,
  $chmod_enable              = $::vsftpd::params::chmod_enable,
  $deny_email_enable         = $::vsftpd::params::deny_email_enable,
  $dirlist_enable            = $::vsftpd::params::dirlist_enable,
  $download_enable           = $::vsftpd::params::download_enable,
  $dual_log_enable           = $::vsftpd::params::dual_log_enable,
  $force_dot_files           = $::vsftpd::params::force_dot_files,
  $force_anon_data_ssl       = $::vsftpd::params::force_anon_data_ssl,
  $force_anon_logins_ssl     = $::vsftpd::params::force_anon_logins_ssl,
  $force_local_data_ssl      = $::vsftpd::params::force_local_data_ssl,
  $force_local_logins_ssl    = $::vsftpd::params::force_local_logins_ssl,
  $guest_enable              = $::vsftpd::params::guest_enable,
  $lock_upload_files         = $::vsftpd::params::lock_upload_files,
  $log_ftp_protocol          = $::vsftpd::params::log_ftp_protocol,
  $mdtm_write                = $::vsftpd::params::mdtm_write,
  $no_anon_password          = $::vsftpd::params::no_anon_password,
  $no_log_lock               = $::vsftpd::params::no_log_lock,
  $one_process_model         = $::vsftpd::params::one_process_model,
  $passwd_chroot_enable      = $::vsftpd::params::passwd_chroot_enable,
  $pasv_addr_resolve         = $::vsftpd::params::pasv_addr_resolve,
  $pasv_enable               = $::vsftpd::params::pasv_enable,
  $pasv_promiscuous          = $::vsftpd::params::pasv_promiscuous,
  $port_enable               = $::vsftpd::params::port_enable,
  $port_promiscuous          = $::vsftpd::params::port_promiscuous,
  $reverse_lookup_enable     = $::vsftpd::params::reverse_lookup_enable,
  $run_as_launching_user     = $::vsftpd::params::run_as_launching_user,
  $secure_email_list_enable  = $::vsftpd::params::secure_email_list_enable,
  $session_support           = $::vsftpd::params::session_support,
  $ssl_enable                = $::vsftpd::params::ssl_enable,
  $ssl_sslv2                 = $::vsftpd::params::ssl_sslv2,
  $ssl_sslv3                 = $::vsftpd::params::ssl_sslv3,
  $ssl_tlsv1                 = $::vsftpd::params::ssl_tlsv1,
  $syslog_enable             = $::vsftpd::params::syslog_enable,
  $tilde_user_enable         = $::vsftpd::params::tilde_user_enable,
  $use_localtime             = $::vsftpd::params::use_localtime,
  $use_sendfile              = $::vsftpd::params::use_sendfile,
  $userlist_log              = $::vsftpd::params::userlist_log,
  $virtual_use_local_privs   = $::vsftpd::params::virtual_use_local_privs,
  $accept_timeout            = $::vsftpd::params::accept_timeout,
  $anon_max_rate             = $::vsftpd::params::anon_max_rate,
  $anon_umask                = $::vsftpd::params::anon_umask,
  $connect_timeout           = $::vsftpd::params::connect_timeout,
  $delay_failed_login        = $::vsftpd::params::delay_failed_login,
  $delay_successful_login    = $::vsftpd::params::delay_successful_login,
  $file_open_mode            = $::vsftpd::params::file_open_mode,
  $ftp_data_port             = $::vsftpd::params::ftp_data_port,
  $local_max_rate            = $::vsftpd::params::local_max_rate,
  $max_login_fails           = $::vsftpd::params::max_login_fails,
  $trans_chunk_size          = $::vsftpd::params::trans_chunk_size,
  $anon_root                 = $::vsftpd::params::anon_root,
  $banned_email_file         = $::vsftpd::params::banned_email_file,
  $cmds_allowed              = $::vsftpd::params::cmds_allowed,
  $listen_address6           = $::vsftpd::params::listen_address6,
  $listen_ipv6               = $::vsftpd::params::listen_ipv6,
  $deny_file                 = $::vsftpd::params::deny_file,
  $dsa_cert_file             = $::vsftpd::params::dsa_cert_file,
  $dsa_private_key_file      = $::vsftpd::params::dsa_private_key_file,
  $email_password_file       = $::vsftpd::params::email_password_file,
  $guest_username            = $::vsftpd::params::guest_username,
  $local_root                = $::vsftpd::params::local_root,
  $message_file              = $::vsftpd::params::message_file,
  $pasv_address              = $::vsftpd::params::pasv_address,
  $rsa_cert_file             = $::vsftpd::params::rsa_cert_file,
  $rsa_private_key_file      = $::vsftpd::params::rsa_private_key_file,
  $secure_chroot_dir         = $::vsftpd::params::secure_chroot_dir,
  $ssl_ciphers               = $::vsftpd::params::ssl_ciphers,
  $user_config_dir           = $::vsftpd::params::user_config_dir,
  $user_sub_token            = $::vsftpd::params::user_sub_token,
  $userlist_file             = $::vsftpd::params::userlist_file,
  $vsftpd_log_file           = $::vsftpd::params::vsftpd_log_file,
  $directives                = {},
) inherits ::vsftpd::params {

  package { $package_name: ensure => installed }

  service { $service_name:
    require   => Package[$package_name],
    enable    => true,
    ensure    => running,
    hasstatus => true,
  }

  file { "${confdir}/vsftpd.conf":
    require => Package[$package_name],
    content => template($template),
    notify  => Service[$service_name],
  }

}

